# task: pose generation
name: epic_kitchen
lr: ${model.learning_rate}
clip_grad: 0.0  # 0.0 means no clip
eval_interval: 1
eval_visualize: 100

train:
  batch_size: 32
  num_workers: 8
  num_epochs: 10000000
  log_step: 100

test:
  epoch: null
  batch_size: 8
  num_workers: 0

dataset:
  name: EpicKitchen
  desc: '[Epic Kitchen]'
  model_type: ${model.name}
  resolution_height: 224
  resolution_width: 224
  aug_window_size: 0.6
  # data_type: rgb  
  data_type: ${model.data_type}
  item_type: ${model.name}
  device: cuda
  data_dir_local: your path to local dataset
  data_dir_slurm:  null

visualizer:
  visualize: false
